repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        stages: [commit]
      - id: go-imports
        stages: [commit]
      - id: go-vet
        stages: [commit]
      - id: go-lint
        stages: [commit]
      - id: go-build
        stages: [commit]
      - id: go-mod-tidy
        stages: [commit]
  - repo: https://github.com/Jerome1337/pre-commit-swaggo-swag
    rev: master
    hooks:
      - id: swag
        stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v3.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
