version: "3.7"

services:
  api:
    container_name: "api-authentication"
    image: golang:latest
    working_dir: /api
    env_file:
      - .env
    volumes:
      - ".:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]

  db:
    container_name: "db-authentication"
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres:/var/lib/postgresql/data"

  adminer:
    container_name: "adminer-authentication"
    image: adminer
    restart: always

volumes:
  postgres:
