version: "3.7"

services:
  api:
    container_name: "api-user"
    image: golang:latest
    working_dir: /api
    env_file:
      - .env
    volumes:
      - ".:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]
    depends_on:
      - db
      - minio

  db:
    container_name: "db-user"
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres:/var/lib/postgresql/data"

  adminer:
    container_name: "adminer-user"
    image: adminer
    restart: always

  minio:
    container_name: "minio-user"
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_ACCESS_KEY}
    command: server /data

volumes:
  postgres:
  minio:
