version: "3.7"

services:
  api:
    container_name: "api-user"
    image: golang:latest
    working_dir: /api
    env_file:
      - .env
    volumes:
      - ".:/api"
    entrypoint: ["./entrypoint.sh", "reflex", "-c", "reflex.conf"]

  db:
    container_name: "db-user"
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - ./scripts/postgres_init.sh:/docker-entrypoint-initdb.d/postgres_init.sh

  adminer:
    container_name: "adminer-user"
    image: adminer
    restart: always

volumes:
  postgres:
